/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.rehkindmag.views;

import com.sun.scenario.Settings;
import java.awt.Component;
import java.util.HashMap;
import java.util.logging.Logger;
import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.JsonStructure;
import javax.json.JsonValue;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JViewport;
import javax.swing.border.EmptyBorder;
import net.rehkind_mag.interfaces.IHttpResponse;
import net.rehkind_mag.interfaces.IHttpResponseReceiver;
import net.rehkind_mag.utils.HttpAccessRequest;
import net.rehkind_mag.utils.UUIDGenerator;
import net.rehkindmag.controls.ClientCase;
import net.rehkindmag.controls.HttpRequestManager;
import net.rehkindmag.controls.UserLogin;

/**
 *
 * @author rehkind
 */
public class CaseAccessView extends javax.swing.JPanel implements IHttpResponseReceiver {
    UUIDGenerator uuidGen = new UUIDGenerator();
    HashMap<Integer, String> pendingHttpRequests=new HashMap<>();
    
    /**
     * Creates new form CaseView
     */
    public CaseAccessView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbEndpoints = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        spCaseViewScreen = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        txtEndpoint = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaRequestBody = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jLabel1.setBackground(new java.awt.Color(150, 150, 150));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 220, 220));
        jLabel1.setText("Cases");
        jLabel1.setOpaque(true);

        cbEndpoints.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "casepool/cases", "casepool/case/{ID}" }));
        cbEndpoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEndpointsActionPerformed(evt);
            }
        });

        jLabel2.setText("select an endpoint:");

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(175, 175, 175)));
        jPanel3.setMaximumSize(new java.awt.Dimension(565656, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        spCaseViewScreen.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(175, 175, 175)));
        spCaseViewScreen.setForeground(new java.awt.Color(30, 60, 30));
        spCaseViewScreen.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spCaseViewScreen)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spCaseViewScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("refine endpoint:");

        txtEndpoint.setToolTipText("variables in endpoint url in same order, comma separated");

        txtaRequestBody.setColumns(20);
        txtaRequestBody.setRows(5);
        jScrollPane1.setViewportView(txtaRequestBody);

        jLabel4.setText("request body:");

        jLabel5.setText("HTTPResponse:");

        jButton1.setText("send HTTP request");
        jButton1.setPreferredSize(new java.awt.Dimension(79, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 75));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 75));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 348, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEndpoints, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtEndpoint)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbEndpoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEndpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbEndpointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEndpointsActionPerformed
        this.txtEndpoint.setText((String)cbEndpoints.getSelectedItem());
    }//GEN-LAST:event_cbEndpointsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HttpRequestManager manager = HttpRequestManager.createHttpRequestManager(Settings.get("server.address"), HttpRequestManager.CONTANT_TYPE_JSON);
        String uuid = uuidGen.getRandomUUIDString();
        //JsonParser parser=Json.createParser(new ByteArrayInputStream(txtaRequestBody.getText().getBytes(Charset.forName("UTF-8"))));
        HttpAccessRequest request = new HttpAccessRequest( txtEndpoint.getText(), uuid, UserLogin.getLoginAsJson(), Json.createObjectBuilder().build() );
        Integer requestID=manager.fireJsonHttpGETRequest(request, this);
        
        pendingHttpRequests.put(requestID, "@GET: "+txtEndpoint.getText()+" uuid="+uuid);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEndpoints;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane spCaseViewScreen;
    private javax.swing.JTextField txtEndpoint;
    private javax.swing.JTextArea txtaRequestBody;
    // End of variables declaration//GEN-END:variables

    @Override
    public void receiveHttpResponse(Integer requestID, IHttpResponse response) {
        Logger.getLogger("global").info("Response for HTTPRequest("+requestID+") received:");
        String request=this.pendingHttpRequests.get(requestID);
        Logger.getLogger("global").info("Request was: "+request);
        Logger.getLogger("global").info("Response is: "+response.getContent().toString());
        this.pendingHttpRequests.remove(requestID);
        
        JsonStructure structContent=((JsonStructure)response.getContent());
        
        for (Component c : spCaseViewScreen.getComponents()){
            if(c.getClass().equals(JPanel.class)){
                spCaseViewScreen.remove(c);
            }
        }
        ClientCase newCase;
        JPanel pCaseViewScreen=new JPanel(true);
        BoxLayout layout = new BoxLayout(pCaseViewScreen, BoxLayout.Y_AXIS);
        pCaseViewScreen.setLayout(layout);
        
        switch (structContent.getValueType()){
            case OBJECT:
                newCase = new ClientCase( (JsonObject)structContent );
                pCaseViewScreen.add(newCase.getCaseNumber(), new CaseView(newCase));
                pCaseViewScreen.setSize(600, 460);
                break;
            case ARRAY:
                int width=600;
                int height=0;
                for ( JsonValue jo : (JsonArray)structContent ){
                    height+=460;
                    newCase = new ClientCase( (JsonObject)jo );
                    pCaseViewScreen.add(newCase.getCaseNumber(), new CaseView(newCase));
                    pCaseViewScreen.setSize(width, height);
                }
                
                break;
            default:
                throw new UnsupportedOperationException("Only JsonObject and JsonArray are supported for http-response body type in CaseAccessView.");
        }
        pCaseViewScreen.setVisible(true);
        int height=pCaseViewScreen.getComponents().length*460;
        pCaseViewScreen.setSize(600,height);
        pCaseViewScreen.validate();
        
        JViewport vport = new JViewport();
        vport.add(pCaseViewScreen);
        
//        spCaseViewScreen.getInsets().set(20, 20, 20, 20);
//        spCaseViewScreen.setViewportBorder(new EmptyBorder(15, 15, 15, 15));
//        spCaseViewScreen.add(pCaseViewScreen);
        spCaseViewScreen.setViewport(vport);
        
        spCaseViewScreen.validate();
        Logger.getLogger("global").info("Pending requests: "+this.pendingHttpRequests.keySet().size());
        Logger.getLogger("global").info("panel size: "+pCaseViewScreen.getSize());
        
    }
    
}
