/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.rehkindmag.views;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MLH
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        pScreen.add("home", new HomeView());
        pScreen.add("case", new CaseAccessView());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        caseBtt = new javax.swing.JButton();
        serviceBtt = new javax.swing.JButton();
        clinicBtt = new javax.swing.JButton();
        submitterBtt = new javax.swing.JButton();
        serviceDefBtt = new javax.swing.JButton();
        homeBtt = new javax.swing.JButton();
        pScreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setSize(new java.awt.Dimension(650, 500));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        caseBtt.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        caseBtt.setText("Cases");
        entityButtons.add(caseBtt);
        caseBtt.setMaximumSize(new java.awt.Dimension(120, 40));
        caseBtt.setMinimumSize(new java.awt.Dimension(79, 40));
        caseBtt.setNextFocusableComponent(serviceBtt);
        caseBtt.setPreferredSize(new java.awt.Dimension(79, 40));
        caseBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseBttActionPerformed(evt);
            }
        });
        jPanel1.add(caseBtt);

        serviceBtt.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        serviceBtt.setText("Services");
        entityButtons.add(serviceBtt);
        serviceBtt.setMaximumSize(new java.awt.Dimension(120, 40));
        serviceBtt.setMinimumSize(new java.awt.Dimension(79, 40));
        serviceBtt.setNextFocusableComponent(clinicBtt);
        serviceBtt.setPreferredSize(new java.awt.Dimension(79, 40));
        jPanel1.add(serviceBtt);

        clinicBtt.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        clinicBtt.setText("Clinics");
        entityButtons.add(clinicBtt);
        clinicBtt.setMaximumSize(new java.awt.Dimension(120, 40));
        clinicBtt.setMinimumSize(new java.awt.Dimension(79, 40));
        clinicBtt.setNextFocusableComponent(submitterBtt);
        clinicBtt.setPreferredSize(new java.awt.Dimension(79, 40));
        jPanel1.add(clinicBtt);

        submitterBtt.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        submitterBtt.setText("Submitter");
        entityButtons.add(submitterBtt);
        submitterBtt.setMaximumSize(new java.awt.Dimension(120, 40));
        submitterBtt.setMinimumSize(new java.awt.Dimension(79, 40));
        submitterBtt.setNextFocusableComponent(serviceDefBtt);
        submitterBtt.setPreferredSize(new java.awt.Dimension(79, 40));
        jPanel1.add(submitterBtt);

        serviceDefBtt.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        serviceDefBtt.setText("ServiceDefs");
        entityButtons.add(serviceDefBtt);
        serviceDefBtt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        serviceDefBtt.setMaximumSize(new java.awt.Dimension(150, 40));
        serviceDefBtt.setMinimumSize(new java.awt.Dimension(120, 40));
        serviceDefBtt.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel1.add(serviceDefBtt);

        homeBtt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        homeBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home_btt_40.png"))); // NOI18N
        homeBtt.setAlignmentX(1.0F);
        entityButtons.add(homeBtt);
        homeBtt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeBtt.setIconTextGap(0);
        homeBtt.setMaximumSize(new java.awt.Dimension(40, 40));
        homeBtt.setMinimumSize(new java.awt.Dimension(79, 40));
        homeBtt.setOpaque(false);
        homeBtt.setPreferredSize(new java.awt.Dimension(40, 40));
        homeBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBttActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtt);

        pScreen.setMinimumSize(new java.awt.Dimension(650, 500));
        pScreen.setPreferredSize(new java.awt.Dimension(650, 500));
        pScreen.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBttActionPerformed
        ((CardLayout)pScreen.getLayout()).show(pScreen, "home");
    }//GEN-LAST:event_homeBttActionPerformed

    private void caseBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseBttActionPerformed
        ((CardLayout)pScreen.getLayout()).show(pScreen, "case");
    }//GEN-LAST:event_caseBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton caseBtt;
    private javax.swing.JButton clinicBtt;
    private javax.swing.ButtonGroup entityButtons;
    private javax.swing.JButton homeBtt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pScreen;
    private javax.swing.JButton serviceBtt;
    private javax.swing.JButton serviceDefBtt;
    private javax.swing.JButton submitterBtt;
    // End of variables declaration//GEN-END:variables
}
