/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.rehkind_mag.views;

import java.awt.Dimension;
import net.rehkind_mag.entities.ClientCase;

/**
 * Displays a single case
 * @author rehkind
 */
public class CaseView extends javax.swing.JPanel {
    ClientCase viewCase;
    /**
     * Creates new form CaseView
     * @param viewCase
     */
    public CaseView(ClientCase viewCase) {
        initComponents();
        this.viewCase=viewCase;
        
        this.lblCaseJson.setVisible(false);
        
        updateView();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCaseJson = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtCaseNumber = new javax.swing.JTextField();
        txtDiagnosis = new javax.swing.JTextField();
        txtSubmitter = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClinic = new javax.swing.JTextField();
        txtEntryDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        setMaximumSize(new java.awt.Dimension(820, 450));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(820, 300));

        lblCaseJson.setForeground(java.awt.SystemColor.textHighlight);
        lblCaseJson.setText("<case as json>");
        lblCaseJson.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        lblCaseJson.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCaseJson.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblCaseJson.setMaximumSize(new java.awt.Dimension(10000, 160));
        lblCaseJson.setMinimumSize(new java.awt.Dimension(109, 160));
        lblCaseJson.setOpaque(true);
        lblCaseJson.setPreferredSize(new java.awt.Dimension(109, 160));
        lblCaseJson.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblID.setLabelFor(txtID);
        lblID.setText("ID:");
        lblID.setMaximumSize(new java.awt.Dimension(150, 30));
        lblID.setMinimumSize(new java.awt.Dimension(150, 30));
        lblID.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setLabelFor(txtCaseNumber);
        jLabel3.setText("Case number:");
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setLabelFor(txtDiagnosis);
        jLabel4.setText("Diagnosis:");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setLabelFor(txtSubmitter);
        jLabel5.setText("Submitter ID:");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(100, 100, 100));
        txtID.setText("<ID>");
        txtID.setMaximumSize(new java.awt.Dimension(100, 30));
        txtID.setMinimumSize(new java.awt.Dimension(100, 30));
        txtID.setPreferredSize(new java.awt.Dimension(75, 30));

        txtCaseNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCaseNumber.setText("<CASE_NUMBER>");
        txtCaseNumber.setMaximumSize(new java.awt.Dimension(150, 30));
        txtCaseNumber.setMinimumSize(new java.awt.Dimension(150, 30));
        txtCaseNumber.setPreferredSize(new java.awt.Dimension(150, 30));
        txtCaseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseNumberActionPerformed(evt);
            }
        });

        txtDiagnosis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiagnosis.setText("<DIAGNOSIS>");
        txtDiagnosis.setMaximumSize(new java.awt.Dimension(400, 30));
        txtDiagnosis.setMinimumSize(new java.awt.Dimension(400, 30));
        txtDiagnosis.setPreferredSize(new java.awt.Dimension(400, 30));

        txtSubmitter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubmitter.setText("<SUBMITTER_ID>");
        txtSubmitter.setMaximumSize(new java.awt.Dimension(400, 30));
        txtSubmitter.setMinimumSize(new java.awt.Dimension(400, 30));
        txtSubmitter.setPreferredSize(new java.awt.Dimension(400, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setLabelFor(txtSubmitter);
        jLabel6.setText("Clinic ID:");
        jLabel6.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel6.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));

        txtClinic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtClinic.setText("<CLINIC_ID>");
        txtClinic.setMaximumSize(new java.awt.Dimension(400, 30));
        txtClinic.setMinimumSize(new java.awt.Dimension(400, 30));
        txtClinic.setPreferredSize(new java.awt.Dimension(400, 30));

        txtEntryDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEntryDate.setText("<ENTRY_DATE>");
        txtEntryDate.setMaximumSize(new java.awt.Dimension(400, 30));
        txtEntryDate.setMinimumSize(new java.awt.Dimension(400, 30));
        txtEntryDate.setPreferredSize(new java.awt.Dimension(400, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setLabelFor(txtSubmitter);
        jLabel7.setText("Entry date:");
        jLabel7.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel7.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 30));

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 10));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 10));
        jPanel1.setPreferredSize(new java.awt.Dimension(32767, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setLabel("Reset");
        jButton1.setMaximumSize(new java.awt.Dimension(107, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(107, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(107, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setLabel("Update");
        jButton2.setMaximumSize(new java.awt.Dimension(107, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(107, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(107, 50));
        jPanel2.add(jButton2);

        jButton3.setLabel("Delete");
        jButton3.setMaximumSize(new java.awt.Dimension(107, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(107, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(107, 50));
        jPanel2.add(jButton3);

        jCheckBox1.setText("show JSON object");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCaseJson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSubmitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtClinic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCaseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubmitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClinic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaseJson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblCaseJson.getAccessibleContext().setAccessibleName("case_json_screen");
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateView();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        this.lblCaseJson.setVisible(jCheckBox1.isSelected());
        Dimension newSize=new Dimension(getWidth(), 300 + ((jCheckBox1.isSelected())?160:0));
        
        this.setMinimumSize(newSize);
        this.setSize(newSize);
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCaseJson;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtCaseNumber;
    private javax.swing.JTextField txtClinic;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtEntryDate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSubmitter;
    // End of variables declaration//GEN-END:variables

    private void updateView() {
        this.lblCaseJson.setText(jsonObjectToHTML( this.viewCase.toString() ));
        this.txtID.setText(""+this.viewCase.getId());
        this.txtID.setSize(100, 30);
        this.txtCaseNumber.setText(this.viewCase.getCaseNumber());
        this.txtDiagnosis.setText(this.viewCase.getDiagnose());
        this.txtSubmitter.setText(""+this.viewCase.getSubmitter().getId());
        this.txtClinic.setText(""+this.viewCase.getClinic().getId());
        this.txtEntryDate.setText( this.viewCase.getEntryDateProperty().getValue());
        
    }
    
    private String jsonObjectToHTML(String rawJson){
        String htmlJson=rawJson;
        htmlJson = htmlJson.replaceAll("\\{", "\\{<br>&nbsp;&nbsp;&nbsp;");
        htmlJson = htmlJson.replaceAll("\\}", "<br>\\}");
        htmlJson = htmlJson.replaceAll(",", "<br>&nbsp;&nbsp;&nbsp;");
        htmlJson = htmlJson.replaceAll(":", ":&nbsp;");
        htmlJson="<html>"+htmlJson+"</html>";
        return htmlJson;
    }
}
